default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: d_admin_development

test:
  <<: *default
  database: d_admin_test

production:
  <<: *default
  database: d_admin
