default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: div__admin_development

test:
  <<: *default
  database: div__admin_test

production:
  <<: *default
  database: div__admin
 